server:
  port: 9983

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flaskexample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # MySQLDialect H2Dialect
  rabbitmq:
    host: localhost # RabbitMQ host ip
    port: 5672 # RabbitMQ port
    username : guest # RabbitMQ 웹 관리 콘솔 아이디
    password: guest # RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: sample-queue # 사용할 queue 이름
  exchange:
    name: sample-exchange # 사용할 exchange 이름
  routing:
    key : key


logging:
  level:
    org.hibernate.SQL: debug

flask:
  base-url: http://localhost:5000/ml/api/  # 로컬 프로파일용 Flask URL
